services:
  db:
    image: mysql:8.0
    container_name: laravel_medical_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: laravel_medical
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-ularavel", "-psecret"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    image: ghcr.io/soul312/laravel_medical:green-blue
    container_name: laravel_medical_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      APP_ENV: production
      APP_DEBUG: true
      APP_KEY: base64:BOTA80AV+7kjFcI31G6a8CJaluUXiFeM6YeQfw/JNWw=
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_medical
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
