name: Simple CI/CD Pipeline

on:
  push:
    branches: [ "Standard" ]

jobs:
  # L'étape de Continuous Integration (CI)
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Prepare Environment
      run: |
        cp .env.example .env
        php artisan key:generate
        mkdir -p tests/Unit

    - name: Run Tests
      # This generates your "Taux d'échec des déploiements" metric. If tests fail, the pipeline stops here.
      run: php artisan test

  # L'étape de Continuous Deployment (CD)
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Render Deployment
      run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
